### ISSUE TITLE
metrics-vg-usage.rb: Check failed to run: Unable to load lvm attributes [lvs.yaml] for version [2.02.166(2)]

### ISSUE THREAD

**Issue by dzeleski** [sensu-plugins/sensu-plugins-lvm#3] opened 2016-11-17 18:01 UTC
Getting the following error on: Red Hat Enterprise Linux Server release 7.3 (Maipo)

Running sensu 0.26.5-2 and plugin version 0.0.1

```
Check failed to run: Unable to load lvm attributes [lvs.yaml] for version [2.02.166(2)]. The version/object may not be supported or you may need to upgrade the di-ruby-lvm-attrib gem. Error [No such file or directory @ rb_sysopen - /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/di-ruby-lvm-attrib-0.0.27/lib/lvm/attributes/2.02.166(2)/lvs.yaml], ["/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/di-ruby-lvm-attrib-0.0.27/lib/lvm/attributes.rb:23:in `rescue in load'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/di-ruby-lvm-attrib-0.0.27/lib/lvm/attributes.rb:20:in `load'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/di-ruby-lvm-0.2.1/lib/lvm/wrapper/lvs.rb:13:in `initialize'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/di-ruby-lvm-0.2.1/lib/lvm/logical_volumes.rb:13:in `new'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/di-ruby-lvm-0.2.1/lib/lvm/logical_volumes.rb:13:in `initialize'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/di-ruby-lvm-0.2.1/lib/lvm.rb:36:in `new'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/di-ruby-lvm-0.2.1/lib/lvm.rb:36:in `initialize'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-lvm-0.0.1/bin/metrics-vg-usage.rb:61:in `new'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-lvm-0.0.1/bin/metrics-vg-usage.rb:61:in `volume_groups'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-lvm-0.0.1/bin/metrics-vg-usage.rb:85:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.4.2/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"]
```

**Comment by eheydrick** [comment] 2016-11-26 22:23
The issue is the 2.02.166(2) support in `di-ruby-lvm-attrib` has yet to be released. I opened issue https://github.com/gregsymons/di-ruby-lvm-attrib/issues/53 to get a new version released.

**Comment by dzeleski** [comment] 2016-11-28 15:04
@eheydrick Awesome thank you!

**Comment by eheydrick** [comment] 2016-12-13 07:29
There is a now a fork of di-ruby-lvm/di-ruby-lvm-attrib by Chef that has been updated with the latest metadata to work on RHEL 7.3. I have updated the plugin to use those gems and tested it on a 7.3 box. Going to get the plugin released and this issue will be resolved.

**Comment by insom** [comment] 2016-12-13 15:03
This new release is pushed. @dzeleski please let me know if this doesn't fix your problem, but I'll close this for now.

**Closed by insom** 2016-12-13 15:03 UTC

**Comment by dzeleski** [comment] 2016-12-15 20:38
@insom getting an error on install:
```
Could not update: Execution of '/opt/sensu/embedded/bin/gem install -v 0.0.3 --no-rdoc --no-ri sensu-plugins-lvm' returned 1: ERROR: Error installing sensu-plugins-lvm: "generate_field_data" from chef-ruby-lvm-attrib conflicts with installed executable from di-ruby-lvm-attrib
```

**Comment by eheydrick** [comment] 2016-12-15 20:49
@dzeleski you'll need to uninstall `di-ruby-lvm-attrib` and `di-ruby-lvm` gems first.

**Comment by dzeleski** [comment] 2016-12-15 20:59
Thats not really ideal when your talking thousands of systems:

```
[root]# /opt/sensu/embedded/bin/gem install -v 0.0.3 --no-rdoc --no-ri sensu-plugins-lvm
chef-ruby-lvm-attrib's executable "generate_field_data" conflicts with di-ruby-lvm-attrib
Overwrite the executable? [yN]  Y
Successfully installed chef-ruby-lvm-attrib-0.0.28
Fetching: chef-ruby-lvm-0.2.2.gem (100%)
Successfully installed chef-ruby-lvm-0.2.2
Fetching: sensu-plugins-lvm-0.0.3.gem (100%)
You can use the embedded Ruby by setting EMBEDDED_RUBY=true in /etc/default/sensu
Successfully installed sensu-plugins-lvm-0.0.3
3 gems installed
```

That works after the fact, but I have to tell it to overwrite obviously. The check also does function but uninstalling that to install this will most likely bug many people including myself, I assumed a clean upgrade would be possible without having to pipe yes to the gem install.

**Comment by dzeleski** [comment] 2016-12-15 21:07
Looks like I can use --force but still not exactly ideal.

```
/opt/sensu/embedded/bin/gem install -v 0.0.3 --no-rdoc --no-ri sensu-plugins-lvm --force
```
